### ISSUE TITLE
wdio cucumber json report shows screenshot as broken image in html report

### ISSUE THREAD

**Issue by gtilekar** [wswebcreation/wdio-cucumberjs-json-reporter#10]
```json
{
  "devDependencies": {
    "@wdio/allure-reporter": "^5.12.1",
    "@wdio/cli": "^5.12.1",
    "@wdio/config": "^5.12.1",
    "@wdio/cucumber-framework": "^5.12.1",
    "@wdio/local-runner": "^5.12.1",
    "@wdio/selenium-standalone-service": "^5.12.1",
    "@wdio/spec-reporter": "^5.12.1",
    "@wdio/sync": "^5.12.1",
    "allure-commandline": "^2.9.0",
    "multiple-cucumber-html-reporter": "^1.12.0",
    "wdio-cucumberjs-json-reporter": "^1.0.8",
    "webdriverio": "^5.12.1"
  }
}
```

feature file
```bash
Feature: Example feature

Scenario Outline: Get title of website
Given I go on the website ""

Examples:
|website|
|www.google.com|
|www.github.com|
|www.gmail.com|

```
stepdef file:

```js
var assert = require('assert')
const { Given, When, Then } = require('cucumber')
const cucumberJson = require('wdio-cucumberjs-json-reporter').default

Given(/^I go on the website "([^"]*)"$/, (url) => {
browser.url(url)
cucumberJson.attach(browser.saveScreenshot('Test.png'), 'image/png')
})

wdio.conf
onComplete: function() {
generate({

  jsonDir: '.tmp/json/',
  reportPath: '.tmp/report/',
});
},
```

HTML report:
![Screen Shot 2019-08-15 at 12 59 10](https://user-images.githubusercontent.com/52917254/63091977-7576db00-bf60-11e9-90cc-e38ab9bd820b.png)

**Updated to proper markdown**

**Comment by robsonpolicarpo** [comment]
Hi @gtilekar !

Have you tried use **takeScreenshot** instead **saveScreenshot**?

**Comment by gtilekar** [comment]
It's same with takeScreenshot()

![Screen Shot 2019-08-15 at 19 43 22](https://user-images.githubusercontent.com/52917254/63114383-05cf1300-bf95-11e9-81cf-0e5cc50bc8d9.png)

**Comment by robsonpolicarpo** [comment]
I think image can't be put in step this way.

This is the code in my conf:

afterStep: (uri, feature, scenario, step, result) => {
        const cucumber = require('cucumber');
        if (result.status === cucumber.Status.FAILED) {
            console.log("FAILED");
            const cucumberJson = require('wdio-cucumberjs-json-reporter').default;
            cucumberJson.attach(browser.takeScreenshot(), 'image/png');
        }
    },

**Comment by gtilekar** [comment]
@robsonpolicarpo Thanks... it works on "wdio-cucumberjs-json-reporter": "^1.0.0"

**Comment by wswebcreation** [comment]
@gtilekar 

This has to do with the fact that you are using an incorrect screenshot method, as @robsonpolicarpo mentioned you should use `browser.takeScreenshot()`, see the examples https://github.com/wswebcreation/wdio-cucumberjs-json-reporter#attachment and also the docs of WebdriverIO 

`saveScreenshot` doesn't return a string, it only saves it to a location
https://webdriver.io/docs/api/element/saveScreenshot.html

`takescreenshot` takes a screenshot, **doesn't** save it but returns a buffer, this is needed for the report
https://webdriver.io/docs/api/webdriver.html#takescreenshot

I'm going to close it for now because this is not an issue with the report
