### ISSUE TITLE
Step not rendering in json due to usage of star notation

### ISSUE THREAD

**Issue by terminalpassion** [wswebcreation/wdio-cucumberjs-json-reporter#15]
* multiple-cucumber-html-reporter 1.13.1
* webdriver 5.11.1
* wdio-cucumberjs-json-reporter 1.1.1
* NodeJS 10.16.0

In our feature files we are not using the traditional 'Given, When, Then' keywords at the beginning of our statements but using '*' (star) notation instead. After our tests run and the report is generated and below is a snippet from that code. In the name property we have the letter 'p' which is the last character of that step.
```json
{
  "arguments": [],
  "keyword": "",
  "name": "p",
  "result": {
    "status": "passed",
    "duration": 10000000
  },
  "line": "",
  "match": {
    "location": "can not be determined with webdriver.io"
  }
}
```
Here is an example of using the traditional statements
```json
{
  "arguments": [],
  "keyword": "Given",
  "name": "I am on a desktop",
  "result": {
    "status": "passed",
    "duration": 10000000
  },
  "line": 9,
  "match": {
    "location": "can not be determined with webdriver.io"
  }
}
```
We have written a large portion of our feature files in star notion which has proven popular amongst our developers. Is there a way of getting name value filed in with the entire step in the report?

**Comment by wswebcreation** [comment]
Hi @terminalpassion 

Thanks for filing an issue and provide all the needed info. This module works in such a way that it uses all the information that is provided by WebdriverIO itself. It will then match if a keyword (language independent) is used and adds that in the to be generated JSON. Because there is no matching keyword, there will be an empty string in the `keyword` output.
The report also doesn't have the context if the `*` is a `Given|When|Then` meaning it can't fill it in without any help from the `outside`, meaning the `@wdio/cucumber-framework` module.

Did it work with WebdriverIO V4?

**Comment by terminalpassion** [comment]
Hi @wswebcreation,

Thanks for your reply which has given the team food for thought. We originally didn't have this in place for WebdriverIO v4. We are currently discussing moving back to Given, When, Then based on this information.

Thanks!

**Comment by wswebcreation** [comment]
Ok, clear, for now I'm going to close it.
