### ISSUE TITLE
Unnecessary Before and After Hook steps

### ISSUE THREAD

**Issue by senovsky** [wswebcreation/wdio-cucumberjs-json-reporter#19]
**Environment:**
 - **Node.js version:** 12.13.0
 - **NPM version:** 6.12.0
 - **webdriver.io version:** 5.16.6
 - **@wdio/cucumber-framework version:** 5.16.6
 - **wdio-cucumberjs-json-reporter version:** 1.1.2

**Config of webdriver.io and the reporter**
See `wdio.conf.js` in my repository

**To Reproduce**
Clone my repository https://github.com/senovsky/cucumber-boilerplate and run those commands:
npm install
./edit-template.sh
npm test

**Describe the bug**
In `.tmp\report.html.json`, there is an unnecessary step added before and after every scenario (Regardless of whether the scenario passed or not).

**Expected behavior**
I would like the Before and After Hook steps to not be added into the `.json` file :-)

**Snapshots**
![wdio-cucumberjs-json-reporter_BeforeHook_AfterHook](https://user-images.githubusercontent.com/49440120/68773702-51dd3280-062c-11ea-9628-fffcae24d362.png)

**Comment by wswebcreation** [comment]
Hi @senovsky 

This is not exactly _unnecessary_ info in the report. Those hooks can be used to set up you environment, you might be able to add attachments there and so on.

I want to keep it in the output because it's part of the CucumberJS process and I would advice you to ask for a change in the used report/create a PR for it.

I'm going to close it for now but it's still open for discussion
