### ISSUE TITLE
Compatibility with WDIO 7.0

### ISSUE THREAD

**Issue by vrudhay** [wswebcreation/wdio-cucumberjs-json-reporter#47]
Compatibility with WDIO 7.0
Hi,
Can I use the same version 2.0.3 of your cucumberjs-json reporter with new WDIO 7.0.x and Cucumber 7.0.x?
Please suggest.

**Comment by grzegorz-jarosz** [comment]
I think you can, but depending on your use case there may be some things missing. I've updated one of my projects and almost everything in the generated JSON report looks fine.

So far I've noticed that "line" entry on a feature file level is generated as "null". After investigating a bit it seems that "uid" from webdriver it no longer has a form of "title + line" number as shown in [example](https://github.com/webdriverio/webdriverio/tree/e9b565e0cb6aeca69d331cbd883734ec72af04f1/packages/wdio-reporter):
`uid: 'I add the following grocieries16'`
After the update it got changed to "feature_file_name:line:column" - for example: 
`uid: "test.feature:2:1"`

And that one I was able to fix at least locally (just created subclass and fixed the method) by updating [`getFeatureDataObject(featureData)`](https://github.com/wswebcreation/wdio-cucumberjs-json-reporter/blob/a6033926ca96f6f2cfb87068202556999b94125c/lib/reporter.js#L229)
and instead of:
`line: parseInt(featureData.uid.substring(featureName.length, featureData.uid.length)),`
i used following lines (note that filename and column) was left unused:
```
const [featureFilename, line, column] = featureData.uid.split(":");

...

line: parseInt(line),
```

Another thing that changed (and I haven't looked at that one, because it haven't break my usage) is that Scenario level steps no longer show location, and `"astNodeId": "2"` is shown there instead.

And the third one I saw is that generated report JSON misses "Hook" as a title in "After" and "Before" hooks, in v7 it's just an empty string.

That's all the changes I found so far, but **apart from that it works just fine**.

**Comment by vrudhay** [comment]
Perfect...
Working now...

I thought after updated from **cucumber** to **@cucumber/cucumber**, you might have also kept 7.0 version.

**Comment by kannanmf** [comment]
I am unable to do npm i wdio-cucumberjs-json-reporter (I am using "webdriverio": "^7.1.1", "@wdio/cucumber-framework": "^7.1.2",)

Getting the below error. Hence not able to use https://www.npmjs.com/package/multiple-cucumber-html-reporter

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test-wdio-v7@1.0.0
npm ERR! Found: @wdio/cucumber-framework@7.1.2
npm ERR! node_modules/@wdio/cucumber-framework
npm ERR!   dev @wdio/cucumber-framework@"^7.1.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @wdio/cucumber-framework@"^6.1.1" from wdio-cucumberjs-json-reporter@2.0.3
npm ERR! node_modules/wdio-cucumberjs-json-reporter
npm ERR!   wdio-cucumberjs-json-reporter@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

Can someone please help on this

**Comment by wswebcreation** [comment]
@kannanmf 

🤔 , strange

When I run a sample project with these dependencies

```json
{
  "name": "cucumberjs",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test.local": "wdio test/configs/wdio.local.chrome.conf.js"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "@wdio/cli": "^7.2.0",
    "@wdio/cucumber-framework": "^7.2.0",
    "@wdio/local-runner": "^7.2.0",
    "@wdio/spec-reporter": "^7.2.0",
    "@wdio/sync": "^7.2.0",
    "chromedriver": "^89.0.0",
    "fs-extra": "^9.1.0",
    "multiple-cucumber-html-reporter": "^1.18.0",
    "wdio-chromedriver-service": "^7.0.0",
    "wdio-cucumberjs-json-reporter": "^2.0.3"
  }
}
```

and install it I get successful logs

```log
 npm i

> fibers@5.0.0 install /Users/wimselles/Sauce/Git/wdio-cucumber-v6-v7/v7/node_modules/fibers
> node build.js || nodejs build.js

`darwin-x64-83` exists; testing
Binary is fine; exiting

> chromedriver@89.0.0 install /Users/wimselles/Sauce/Git/wdio-cucumber-v6-v7/v7/node_modules/chromedriver
> node install.js

ChromeDriver binary exists. Validating...
ChromeDriver is already available at '/var/folders/vg/lfm83td92t921fbqjrxrs4ym0000gp/T/89.0.4389.23/chromedriver/chromedriver'.
Copying to target path /Users/wimselles/Sauce/Git/wdio-cucumber-v6-v7/v7/node_modules/chromedriver/lib/chromedriver
Fixing file permissions.
Done. ChromeDriver binary available at /Users/wimselles/Sauce/Git/wdio-cucumber-v6-v7/v7/node_modules/chromedriver/lib/chromedriver/chromedriver

> @fortawesome/fontawesome-common-types@0.2.35 postinstall /Users/wimselles/Sauce/Git/wdio-cucumber-v6-v7/v7/node_modules/@fortawesome/fontawesome-common-types
> node attribution.js

Font Awesome Free 0.2.35 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)


> @fortawesome/fontawesome-svg-core@1.2.35 postinstall /Users/wimselles/Sauce/Git/wdio-cucumber-v6-v7/v7/node_modules/@fortawesome/fontawesome-svg-core
> node attribution.js

Font Awesome Free 1.2.35 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)


> @fortawesome/free-solid-svg-icons@5.15.3 postinstall /Users/wimselles/Sauce/Git/wdio-cucumber-v6-v7/v7/node_modules/@fortawesome/free-solid-svg-icons
> node attribution.js

Font Awesome Free 5.15.3 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)


> core-js-pure@3.9.1 postinstall /Users/wimselles/Sauce/Git/wdio-cucumber-v6-v7/v7/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"


> protobufjs@6.10.2 postinstall /Users/wimselles/Sauce/Git/wdio-cucumber-v6-v7/v7/node_modules/protobufjs
> node scripts/postinstall

npm WARN cucumberjs@1.0.0 No repository field.

added 581 packages from 714 contributors and audited 582 packages in 8.123s

67 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

What version of Node are you on? I'm on `v14.15.3` and npm `6.14.9`

**Comment by kannanmf** [comment]
Thanks for your reply @wswebcreation 
I am using node v14.16.0 and npm 7.6.2

**Comment by kannanmf** [comment]
@wswebcreation 
It's working fine after I downgrade my npm version to 6.14.X

Able to generate html report using multiple cucumber html report

Thanks for your hint.

**Comment by wswebcreation** [comment]
Closing this one because this module can work with WDIO V7
